### ISSUE TITLE
Search by ID

### ISSUE THREAD

**Issue by kirillVv** [ricklancee/maljs#4]
Good day,

is there any way to search for entrie by Id ? Would be cool to have this feature.

**Comment by ricklancee** [comment]
Since this is just a simple wrapper for the official MyAnimeList API it's doesn't support searching by ID as it only implements endpoints that are documented here https://myanimelist.net/modules.php?go=api

Side note: The MAL developers are going to overhaul the entire API so in the future (see https://myanimelist.net/forum/?topicid=1632480), then i'll update this wrapper to support any new API endpoints.  

You could look into one of the many unoffical MAL api's that support searching by ID.

GL!
